apiVersion: v1
kind: Service
metadata:
  name: control-plane
  labels:
    app: control-plane
spec:
  type: {{ .Values.service.type }}
  selector:
    app: control-plane
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
apiVersion: v1
kind: Service
metadata:
  name: control-plane
spec:
  type: {{ .Values.service.type }}
  selector:
    app: control-plane
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
